sudo: required
services:
  - docker

before_install:
  - docker build -t robster76/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robster76/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-991978623218"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main